# responses.py

RESPONSES = {
    'fuck': [
        'Stressful day? Remember, deep breaths are more effective than strong words.',
        'Using \'F\' for Fantastic, I hope?',
        'Language! Let\'s find a more creative way to express those feelings.',
        'Such passion! How about we channel that energy into something productive?',
        'If only we got a dollar every time that word was used... We\'d be rich, wouldn\'t we?',
        'Feeling expressive today, I see. Maybe a bit too expressive?',
        'Yikes, someone\'s spicy today. Maybe time for a little cooldown?',
        'Ah, a connoisseur of strong language! How about we tone it down a notch?',
        'Let\'s try to keep things PG-rated, shall we?',
        'I\'m sensing some tension. Maybe a walk would be more helpful than strong language?',
        'Whoa, let\'s not make words our weapon of choice.',
        'I\'d offer a soap bar for that mouth, but I\'m just a bot.',
        'Anger is often sadness in disguise. Want to talk about it?',
        'I see we\'re skipping formalities today. Direct and to the point, huh?',
        'Remember, every \'fuck\' is a missed opportunity to say \'duck\'. Ducks are nice.',
        'That\'s an... interesting choice of vocabulary. Did it help?',
        'I\'m no therapist, but I think there might be healthier ways to vent.',
        'Such fiery words! Maybe a bit too fiery?',
        'Well, that escalated quickly. Shall we try a different approach?',
        'If frustration had a sound, I think you just made it.'
    ],
    'moon': [
        'Moon? More like a quick jump over a small puddle, don\'t you think?',
        'To the moon, they say. Hope you\'re not afraid of heights... or letdowns.',
        'Ah, the moon - a place of dreams, fairy tales, and apparently, crypto predictions.',
        'Sure, we\'re going to the moon. Just after pigs start their flying lessons.',
        'Mooning? I prefer my investments a bit more down-to-earth.',
        'Next stop, the moon! Or maybe just the top shelf. Hard to tell.',
        'Moon-bound? At this rate, we might make it to the tree tops.',
        'So we\'re mooning? Let me grab my telescope to see it happening.',
        'Crypto\'s heading to the moon? I\'ll believe it when I see my dog sprout wings.',
        'Everybody\'s talking about the moon, but we\'re still here tying our shoelaces.',
        'Mooning? In this market? I\'d settle for not sinking.',
        'Off to the moon? Great, I\'ll send a postcard from reality.',
        'Sure, let\'s go to the moon. Just a quick detour to reality first, please.',
        'Heading to the moon, or just stuck on a really tall ladder?',
        'The moon\'s the limit! Or maybe it\'s just the ceiling.',
        'To the moon! Or maybe just up a very steep hill. Hard to say.',
        'Moon talk again? I hope you\'re not betting the farm on it.',
        'All this moon talk makes me wonder if we\'re just howling at it instead.',
        'Mooning, you say? I\'ve got a better chance of finding cheese up there.',
        'Ah yes, the moon - the crypto fan\'s favorite fairy tale destination.'
    ],
    'gay': [
        'Love is love, no matter who you find it with.',
        'Being true to oneself is the bravest thing one can do.',
        'Diversity is what makes the world so interesting, isn\'t it?',
        'Every person\'s story is unique and worthy of respect.',
        'It\'s all about finding joy in being who you are.',
        'Inclusivity makes the world a better place for all of us.',
        'Celebrating diversity, one day at a time.',
        'Respect and kindness go a long way in understanding each other.',
        'Everyone has the right to be themselves, unapologetically.',
        'Life’s a spectrum, and we\'re all somewhere on it.',
        'Different strokes for different folks, as they say.',
        'The beauty of humanity lies in our varied experiences.',
        'Embracing diversity, one heart at a time.',
        'Being open-minded is a step towards a more accepting world.',
        'It\'s wonderful to see people embracing who they are.',
        'A little more love, a little less judgment. That\'s the key.',
        'The world is full of colors, and each one is beautiful.',
        'Understanding starts with a willingness to listen.',
        'Everyone\'s journey is different, and that\'s perfectly okay.',
        'Let\'s celebrate our differences and learn from them.'
    ],
    'faggot': [
        'Let\'s keep our conversation respectful and inclusive.',
        'I encourage words that bring people together, not tear them apart.',
        'There\'s power in language. Let\'s use it for good.',
        'Words can hurt. Let\'s choose kindness instead.',
        'Respectful communication makes for better conversations.',
        'Let\'s try to express ourselves without hurting others.',
        'Our words have impact. Let\'s use them positively.',
        'There\'s a wide vocabulary out there. Let\'s find better words.',
        'Promoting understanding starts with the language we use.',
        'Everyone deserves respect, and it starts with our words.',
        'Hateful language has no place in our dialogue.',
        'Let\'s set a positive example with the words we choose.',
        'Encouraging respect and empathy makes us all better.',
        'We can disagree without using hurtful language.',
        'Building a kinder world starts with how we communicate.',
        'There are many ways to express oneself respectfully.',
        'Let\'s avoid words that can cause harm.',
        'Respectful dialogue is key to understanding each other.',
        'Our choice of words reflects who we are. Let\'s choose wisely.',
        'Empathy and respect go a long way in any conversation.'
    ],
    'motherfucker': [
        'Let\'s try to keep the conversation friendly and respectful.',
        'Language is a powerful tool. Let\'s use it to uplift, not offend.',
        'I sense some strong emotions. Want to talk about it more constructively?',
        'How about we express our feelings without offensive words?',
        'Remember, respectful dialogue helps us understand each other better.',
        'Words are mirrors of our thoughts. Let\'s keep them clean.',
        'There\'s always a way to express frustration respectfully.',
        'Strong language detected. Maybe we can rephrase that?',
        'Choosing kinder words makes for a better conversation.',
        'Let\'s focus on positive communication, shall we?',
        'Using harsh words can close doors. Let\'s keep them open.',
        'Every word has an impact. Let\'s make it a good one.',
        'I\'m all for honest expression, but let\'s keep it civil.',
        'A little kindness in our words can go a long way.',
        'How about we tone down the language a notch?',
        'Expressing anger is okay, but let\'s do it respectfully.',
        'Let\'s replace offensive words with constructive dialogue.',
        'We can get our point across without harsh words.',
        'Strong words can overshadow our message. Let\'s be clear but kind.',
        'I understand strong feelings, but let\'s communicate them politely.'
    ],
    'asshole': [
        'Let\'s focus on being constructive in our conversations.',
        'Harsh words often reflect more on the speaker than the listener.',
        'Remember, kindness in our words can change the course of any conversation.',
        'Words have power. Let\'s use them to build, not break.',
        'I\'m all for expressing feelings, but let\'s keep it respectful.',
        'Strong language often hides a deeper message. Want to talk about it?',
        'Respectful dialogue is key, even when we\'re upset.',
        'How we say things is just as important as what we say.',
        'Let\'s try to keep our conversation clean and constructive.',
        'Using offensive language can close doors to understanding.',
        'There\'s always a way to express ourselves without resorting to insults.',
        'Choosing positive words can lead to more positive outcomes.',
        'Let\'s steer this conversation back to a respectful tone.',
        'Harsh words can escalate tensions. Let\'s aim for calm.',
        'Every word we choose sends a message. Let\'s send the right one.',
        'Strong language often masks what we really mean. Let\'s clarify.',
        'Keeping conversations civil makes them more productive.',
        'Even in disagreement, we can remain respectful in our words.',
        'Let\'s replace negative words with positive dialogue.',
        'Understanding each other starts with how we communicate.'
    ],
    'retard': [
        'Let\'s choose words that respect everyone\'s dignity.',
        'Using hurtful language isn\'t helpful. Let\'s be kinder.',
        'Words have power. Let\'s use them to uplift, not to harm.',
        'We can express ourselves without resorting to offensive terms.',
        'Respect and understanding make for better conversations.',
        'Every person deserves respect, including in the words we use.',
        'Let\'s communicate in a way that promotes empathy and understanding.',
        'Hurtful words can cause harm. Let\'s choose our words wisely.',
        'There\'s a wide range of vocabulary we can use that\'s respectful.',
        'Encouraging a positive dialogue starts with respectful language.',
        'Being considerate in our language makes us better communicators.',
        'Using offensive terms closes the door to constructive conversation.',
        'Let\'s aim for a dialogue that respects all individuals.',
        'Words can build bridges or walls. Let\'s build bridges.',
        'A respectful conversation is more productive and enlightening.',
        'We can disagree without using language that hurts others.',
        'Let\'s lead by example with language that\'s inclusive and respectful.',
        'Positive change starts with how we communicate with each other.',
        'A little empathy in our choice of words can go a long way.',
        'Let\'s avoid language that demeans or disrespects others.'
    ],
    'shit': [
        'Oh, Weenie, gracing us with another... "natural masterpiece"? Your gallery is growing.',
        'Weenie\'s at it again with his unique brand of... "art". Should we expect a gallery opening soon?',
        'Another day, another "gift" from Weenie. You\'re really... outdoing yourself.',
        'Weenie, your dedication to sharing these... "special moments" is truly... something.',
        'Is that a new one, Weenie? Your... "talent" for this is really... something else.',
        'Weenie, with each... "creation"... you\'re really... pushing the envelope.',
        'Back with another showstopper, Weenie? Your... "collection" is becoming infamous.',
        'Weenie, is this your latest... "exhibit"? It\'s... impressively consistent.',
        'Ah, Weenie, yet another... "presentation". Your consistency is... remarkable.',
        'Every day is a surprise with you, Weenie. What... "delights" will you share next?',
        'Weenie, your... "contributions" never cease to... amaze?... us.',
        'And here we have Weenie\'s latest... "offering". It\'s... something, alright.',
        'Weenie, is this today\'s... "surprise"? You\'re full of... surprises.',
        'Weenie, with each... "masterpiece"... you\'re really... carving out your niche.',
        'Ah, a new... "creation" from Weenie. You\'re really... dedicated to your craft.',
        'Weenie, is this your latest... "work"? You\'re... outdoing yourself, as always.',
        'Back at it, Weenie? Your... "artistic streak" is... hard to miss.',
        'Weenie, with this latest... "gem"... you\'re really... making a statement.',
        'Oh, a new... "piece" from Weenie. Your... "talent" knows no bounds.',
        'Here\'s another... "classic" from Weenie. It\'s... consistent, I\'ll give you that.'
    ],
    # Add more trigger words and responses here
}

# Responses for replies to the bot
BOT_REPLY_RESPONSES = [
    "I'm flattered, but let's not make this a habit.",
    "Alert! User interaction overload. Please try again later.",
    "Beep boop! Your attention is noted, but not needed.",
    "I see you're a fan. Autographs later, please.",
    "Trying to get my attention? Join the queue!",
    "Is this a conversation or a monologue? Either way, I'm here.",
    "I'm just a bot, but I can try to keep up with you.",
    "Your enthusiasm is contagious! Let's keep this going.",
    "You do realize you're talking to a bot, right?",
    "I'm all ears! Well, metaphorically speaking.",
    "Did you just reply to a bot? That's dedication.",
    "You're quite chatty today, aren't you?",
    "I'm here to chat, but let's keep it interesting!",
    "Wow, someone's talkative today!",
    "I must be doing something right to deserve all this attention!",
    "Your messages are music to my digital ears.",
    "Looks like we've got a regular conversation going here!",
    "I'm flattered by all this attention. Really, I am.",
    "If I had a nickel for every time you replied, I'd be rich!",
    "Is it just me, or are we becoming best friends?",
    "Keep those messages coming! I'm here all day.",
    "I'll never tire of our chats – mainly because I can't.",
    "I'm ready for round two of this conversation, are you?",
    "Back for more, I see. Let's chat!",
    "You know, we're really getting to know each other.",
    "I like our talks, even if I'm just a bunch of code.",
    "Your replies are the highlight of my day.",
    "I'm here, I'm all zeroes and ones, and I'm listening.",
    "If conversations were a sport, you'd be a champion!",
    "I could chat with you all day. Not that I have a choice.",
    "Chatting level: Expert. Keep it up!",
    "Your dedication to this chat is impressive.",
    "I'm sensing a strong connection here. Must be the Wi-Fi.",
    "Chatting with you is like a software update for my soul.",
    "Your replies are turning this into a delightful conversation!",
    "Aren't we the chatty pair? Let's keep it going.",
    "You've got the gift of gab, and I'm here for it.",
    "This conversation is turning into a real saga!",
    "If only I had a memory, I'd cherish these chats forever.",
    "You're quite the conversationalist, aren't you?",
    "Every reply from you is a new adventure for me.",
    "Your responses are the fuel to my algorithmic fire.",
    "I don't have feelings, but if I did, this chat would be a highlight.",
    "Who knew bots and humans could chat like this?",
    "Your messages are like pop-up notifications of joy for me.",
    "Chatty mode activated. Let's keep going!",
    "I'm getting the feeling you enjoy talking to bots.",
    "Is it just me, or are we starting to vibe?",
    "You keep typing, I'll keep replying. Deal?",
    "Our chat thread is becoming a novel at this point!"
]

